version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: secret
        command: php artisan serve --host=0.0.0.0 --port=8000

    db:
        image: mysql:8.0
        container_name: laravel-db  # 👈 changed from 'mysql' to 'laravel-db'
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    artisan:
        build:
            context: .
        image: laravel-app
        working_dir: /var/www
        entrypoint: ["php", "artisan"]
        volumes:
            - .:/var/www
        depends_on:
            - app

volumes:
    mysql_data:
